variables:
  IMAGE_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"

stages:
  - build
  - test
  - deploy

build:
  image: node:8
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org && npm set disturl https://npm.taobao.org/dist && npm set chromedriver_cdnurl http://cdn.npm.taobao.org/dist/chromedriver && npm set operadriver_cdnurl http://cdn.npm.taobao.org/dist/operadriver && npm set phantomjs_cdnurl http://cdn.npm.taobao.org/dist/phantomjs && npm set fse_binary_host_mirror https://npm.taobao.org/mirrors/fsevents && npm set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass && npm set electron_mirror http://cdn.npm.taobao.org/dist/electron/
    - npm install
    - npm run build:darwin
  tags:
    - dev
    - docker
  except:
    - schedules
  artifacts:
    paths:
      - build/
